version: '3'

services:
  socketio:
    build: .
    networks:
      - nginx_network
    ports:
      - 3101:3101
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: knguyen
    networks:
      - nginx_network
    ports:
      - 27017:27017

networks:
  nginx_network:
    external: true
